CHANGELOG.md
lib/raygun4flutter.dart

`setUserId` should only accept `String?` rather than `dynamic`.

Cleanup setUserId

---

.github/workflows/main.yml
README.md
analysis_options.yaml
example/lib/main.dart
example/pubspec.lock
example/pubspec.yaml
example/test/widget_test.dart
lib/raygun4flutter.dart
pubspec.lock
pubspec.yaml
test/raygun4flutter_test.dart

Fixes https://github.com/MindscapeHQ/raygun4flutter/issues/6
Adds CI checks for:
- format (job will fail if formatting is wrong)
- analyze (using the lint package)
- test
Checks will run on PRs and on master.
Also added tests that cover the basic dart code (native code is still not tested).
As well as badges showing the build status and the release version.

GitHub Actions Setup

---

CHANGELOG.md
android/src/main/kotlin/com/raygun/raygun4flutter/raygun4flutter/Raygun4flutterPlugin.kt
lib/raygun4flutter.dart
lib/src/raygun_breadcrumb_message.dart
test/raygun4flutter_test.dart

In this PR:
* Add method to record breadcrumbs as custom object
* Add method to clear breadcrumbs.
* Add method setCustomCrashReportingEndpoint
Merge to `develop`!
iOS changes will come in another separated PR!

Completed API changes for Android

---

README.md

Documentation updates to match current version and Android native hooks

V1 doc updates for android

---

example/ios/Podfile.lock
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
example/lib/main.dart
ios/Classes/SwiftRaygun4flutterPlugin.swift
ios/raygun4flutter.podspec
lib/raygun4flutter.dart
lib/src/raygun_breadcrumb_message.dart
lib/src/raygun_user_info.dart

Some important changes:
- Marked the `raygun4apple` to version `1.5` (the current one)
- Because in the custom User data on iOS the `identifier` must not be null, I had to update the dart side and make it a required param.
This would complete the work for the "feature complete" crash reporting.
Only updating pubspec and changelog and we are good to go :)

iOS implementation of new plugin API

---

README.md
lib/src/raygun_user_info.dart
pubspec.yaml

Some tiny doc improvements and fixing 2 issues pub.dev reporting in the scoring section. This should bump us to 120/130.

Some small post-0.5 fixes

---

example/pubspec.lock
lib/raygun4flutter.dart
lib/src/raygun_crash_reporting.dart
lib/src/services/crash_reporting_post_service.dart
lib/src/services/settings.dart
pubspec.lock
pubspec.yaml

- Store crash report payload if no connectivity or failed to send
- send stored payloads on connectivity change
- send stored on init

Fix #36 support storing and sending cached payloads

---

lib/src/messages/raygun_environment_message.dart

See https://github.com/MindscapeHQ/raygun4flutter/issues/31

Add utc offset

---

example/pubspec.lock
lib/src/messages/raygun_app_context.dart
lib/src/messages/raygun_app_context.g.dart
lib/src/raygun_crash_reporting.dart
pubspec.lock
pubspec.yaml

- Remove platform channel (#26)
- setup http json (#28)
- Fix #34 load breadcrumbs in crash report
- Fix all tests
- Fix #33 load ip and network status (#37)
- Fix #32 - add app context

add app context

---

CHANGELOG.md
example/analysis_options.yaml
lib/raygun4flutter.dart
lib/src/messages/network_info.dart
lib/src/messages/raygun_breadcrumb_message.dart
lib/src/messages/raygun_breadcrumb_message.g.dart
lib/src/services/crash_reporting_post_service.dart
lib/src/services/settings.dart
pubspec.yaml
test/raygun4flutter_test.dart

- fix analyze on example project
- Fix #47 breadcumbs order change
- Fix #46 add timestamp to breadcrumbs

Fix #46 #47 improved breadcrumbs"

---

CHANGELOG.md
README.md
example/pubspec.lock
example/pubspec.yaml
pubspec.lock
pubspec.yaml

- Upgrade dependencies
- version bump
- Update changelog

Upgrade dependencies and version bump

---

example/macos/Flutter/GeneratedPluginRegistrant.swift
example/pubspec.lock
lib/raygun4flutter.dart
lib/src/messages/network_info.dart
lib/src/services/crash_reporting_device.dart
lib/src/services/crash_reporting_post_service.dart
lib/src/services/settings.dart
pubspec.lock
pubspec.yaml
test/raygun4flutter_test.dart

- Upgrading plus packages to the latest version.
- Support multiple connectivity values.

feat!: Upgrade major dependencies and support multiple connectivity values

---

CHANGELOG.md
README.md
example/pubspec.lock
pubspec.yaml

release: Version 3.0.0

---

CHANGELOG.md
pubspec.yaml

- **Purpose**: Prepare release 3.0.2
- **Approach**: Update pubspec and changelog
**Updates**
- Bump version on `pubspec.yaml`
- Updated CHANGELOG
- Run `flutter pub publish --dry-run` without warnings

chore: Version 3.0.2

---

example/.gitignore
lib/src/messages/raygun_breadcrumb_message.g.dart
lib/src/messages/raygun_environment_message.g.dart
lib/src/messages/raygun_error_message.dart
lib/src/messages/raygun_error_stack_trace_line_message.dart
lib/src/messages/raygun_error_stack_trace_line_message.g.dart
pubspec.lock

- **Purpose**: Adds missing `columnNumber` property to stack trace object
- **Approach**: Add the missing property
- Related: #61 
**Updates**
- Add property.
- Re-generate code (this affects other files as well)
- Tested using example project
Results:
```json
"stackTrace": [
{
"lineNumber": 6971,
"className": "",
"fileName": "[http://localhost:37075/main.dart.js"](http://localhost:37075/main.dart.js),
"methodName": "Object.Cf",
"columnNumber": 18
},
{
"lineNumber": 57311,
"className": "",
"fileName": "[http://localhost:37075/main.dart.js"](http://localhost:37075/main.dart.js),
"methodName": "a_s.$0",
"columnNumber": 47
},
{
"lineNumber": 41483,
"className": "",
"fileName": "[http://localhost:37075/main.dart.js"](http://localhost:37075/main.dart.js),
"methodName": …
```

fix: Add `columnNumber` to stack trace

---

lib/raygun4flutter.dart

- **Purpose**: Just a typo I noticed
- **Approach**: 
**Updates**
- fix typo
- None

docs: fix typo in method doc

---

README.md

- **Purpose**: Adds documentation regarding Source Maps support
- **Approach**: Edited README.md
**Updates**
- Edited README.md
- None

docs: #61 Add Source Map documentation to README.md

---

CHANGELOG.md
example/pubspec.lock
pubspec.yaml

- **Purpose**: What issue does this PR address or what feature does it implement?
- **Approach**: How does this PR tackle the problem?
**Updates**
- Updated `pubspec.yml` with version bump
- Updated `CHANGELOG.md` with changes list
- Run `flutter pub get` (updated the example `pubspeck.lock`)
- Performed `flutter pub publish --dry-run`

chore: Prepare Release 3.1.0

---

.gitignore
lib/src/messages/raygun_environment_message.dart
lib/src/messages/raygun_environment_message.g.dart
lib/src/utils/_device_info_util_device.dart

- **Purpose**: Adds the architecture value to the environment payload
- **Approach**: Uses Dart's native platform ABI info.
**Updates**
- Parses ABI value, extracting the arch from the second part of the string.
- Adds extra info from Flutter's `Platform` object.
- Passes both the Android OS version and the SDK version.
- Passes both the iOS version and the system version as SDK version.
As shown on Raygun:
- Tested on Linux, Android, macOS and iOS.
- Unit tests are not applicable because the native platform is mocked in tests.

fix: #31 Improve Environment details

---

CHANGELOG.md
example/pubspec.lock
pubspec.lock
pubspec.yaml

- **Purpose**: Prepare release 3.2.1
- **Approach**: Updated pubspec, changelog and tested publish in dry mode
**Updates**
- Bump version in `pubspec.yaml`.
- Updated `CHANGELOG.md`.
- Run `flutter pub get` to update `.lock` files.
Run `flutter pub publish --dry-run` without issues.

chore: Prepare release 3.2.0

---

.gitignore
CHANGELOG.md
README.md
example/lib/main.dart
example/pubspec.lock
lib/raygun4flutter.dart
lib/src/messages/raygun_environment_message.dart
lib/src/messages/raygun_environment_message.g.dart
lib/src/messages/raygun_error_message.dart
lib/src/raygun_crash_reporting.dart
lib/src/utils/_device_info_util_device.dart
pubspec.lock
pubspec.yaml
test/raygun4flutter_test.dart

**DO NOT SQUASH MERGE**
- **Purpose**: Merge to master PR
**Updates**
See CHANGELOG

chore: Release merge 3.2.0

---

CHANGELOG.md
lib/src/services/settings.dart
pubspec.yaml

- **Purpose**: Prepare release 3.2.1
- **Approach**: How does this PR tackle the problem?
**Updates**
- Updated pubspec
- Updated version in code
- Updated changelog
- Run `flutter pub publish --dry-run`

chore: prepare 3.2.1

---

README.md

- **Purpose**: Improve the README 
- **Approach**: doc update
**Updates**
- Removed mention to the <1.0.0 version, as should not be relevant anymore.
- Added links to other raygun providers
None
None

docs: Update README.md with native plugins links
